### ISSUE TITLE
missing surface vehicle models?

### ISSUE THREAD

**Issue by tve** [daneshtarapore/gazebo-asv#1]
I get the following error when trying your example (set-up for 2 ASVs):
```
[Wrn] [ModelDatabase.cc:340] Getting models from[http://gazebosim.org/models/]. This may take a few seconds.
[Err] [ModelDatabase.cc:414] Unable to download model[model://surfacevehicle_0]
[Err] [SystemPaths.cc:430] File or path does not exist[""]
Error [parser.cc:582] Unable to find uri[model://surfacevehicle_0]
[Err] [ModelDatabase.cc:414] Unable to download model[model://surfacevehicle_1]
[Err] [SystemPaths.cc:430] File or path does not exist[""]
Error [parser.cc:582] Unable to find uri[model://surfacevehicle_1]
```
Did you perhaps forget to commit those files to the repo?

**Comment by tve** [comment]
I found how to generate them (I overlooked that part of the instructions in the README). Now the error I still see is
```
[Err] [msgs.cc:3242] Invalid sensor noise type[custom]. Using 'none'.
```
Also, while I see the ground/ceiling/wall planes, the surfacevehicles are not visible in the simulation and doing a "follow" causes everything to spin.

**Comment by tve** [comment]
I was missing some env vars in order for gazebo to find the surface boat meshes. Now I see the boats in the simulation, pretty cool! I still see the sensor noise error.

**Comment by daneshtarapore** [comment]
Thanks for your interest in the simulator. 

What version of Gazebo are you using? Is it Gazebo 8? I do not see the sensor noise error with Gazebo 7. It seems there are quite a few changes in gazebo plugin functionality in the new version. Updating the simulator for Gazebo 8 will now be part of the todo list.

The simulator is still in development, and one of the functions I will be looking into next is sensor plugins. Also, please remember to compile the GPS plugin before running the simulator (was not mentioned in the readme as the functionality has not been fully implemented).

**Comment by tve** [comment]
Yes, I am using Gazebo 8. Do I understand correctly that your simulation cannot really adapt to ocean waves? I assume you are mostly interested in higher-level navigation and less in the boat behavior in waves?

I did compile and include the GPS plugin.

I'm looking into whether I have the appetite to implement http://www.gamasutra.com/view/news/237528/Water_interaction_model_for_boats_in_video_games.php and http://www.gamasutra.com/view/news/263237/Water_interaction_model_for_boats_in_video_games_Part_2.php (which are amazing articles).

**Comment by daneshtarapore** [comment]
Thanks for sharing the articles.

> Yes, I am using Gazebo 8. Do I understand correctly that your simulation
> cannot really adapt to ocean waves? I assume you are mostly interested in
> higher-level navigation and less in the boat behavior in waves?
>

Yes, it can adapt to ocean waves, perhaps with some tweaks to the buoyancy
plugin. However, simulating realistic and visually appealing ocean waves is
not at all trivial, specially if you are talking about a large swarm of
ASVs running at 50x real-time. If you have some ideas on how to do it,
please let me know. Otherwise, simply simulating the resulting damped
oscillatory forces on the robot platform is an easier solution.

I am interested in fault-recovery at the level of the swarm. How can robots
of the swarm recover rapidly (in the order of minutes) from sustained
damages. So realistic boat behavior with/without waves is important to me.

Have you looked at UWSim; it is for underwater robots (
http://www.irs.uji.es/uwsim/), but they also support surface vehicles.

Best,
Danesh.

**Comment by tve** [comment]
If you're interested in a swarm then I understand (although the simulation of multiple boats should be embarrassingly parallel). I'm more interested in a control algorithm to steer a very fast & small USV over waves without crashing... If I get anywhere it'll be on github. Thanks for the uwsim pointer.

**Comment by daneshtarapore** [comment]
On Mon, Aug 14, 2017 at 9:05 PM, Thorsten von Eicken <
notifications@github.com> wrote:

> If you're interested in a swarm then I understand (although the simulation
> of multiple boats should be embarrassingly parallel). I'm more
>
Again, not necessarily. For instace, simulating collisions and "tugging"
behaviours, of a swarm of smaller boats guiding a large boat to a desired
position. But yes, some palletization is offcourse possible.


> interested in a control algorithm to steer a very fast & small USV over
> waves without crashing... If I get anywhere it'll be on github. Thanks for
> the uwsim pointer.
>
Yes, I would be very interested in seeing reliable simulations of highly
manoeuvrable USVs.

I had looked at uwsim a while back. Now that I recall, there model of
buoyancy is very simple -- assumes a spherical body completely submerged in
water; not very useful for what you want.
